### ISSUE TITLE
Pipe Priorities not working with Tech Reborn Tanks

### ISSUE THREAD

**Issue by duncanwebb** [AztechMC/Modern-Industrialization#118]
Version: Modern-Industrialization-0.4.0-alpha.10
Fabric API: 0.11.3

Not sure what the expected behaviour is, this is what happens. Using all MI tanks, then the flow works as expected.

https://user-images.githubusercontent.com/4198031/130816113-42a7ccc6-37ea-4a29-a187-df44feabc427.mp4

Earlier, instead of the steel tank there was an automatic trash can and I wondered why the tech reborn tank wasn't getting filled.

The other behaviour that is different between MI tanks and TR tanks is what happens to the connection when a tank is dropped.

https://user-images.githubusercontent.com/4198031/130816643-8f34dbeb-20a2-49f6-9edd-ebabb58b4117.mp4

I like the behaviour of the tech reborn tank, if it is broken, then the connection is also broken.

Your mod is excellent, many thanks.

**Comment by Technici4n** [comment]
I can't reproduce the former issue in 1.17, so I'll assume this is due to either a bad implementation in MI which has been fixed since, or an issue with the way fluids used to work in 1.16.

Regarding connections, the correct behavior is that the connection should be removed, but TR doesn't send a neighbor block update so MI can't know that the tank was removed. (TechReborn/TechReborn#2484)

However, keeping the connection might be better, I'll look into it.

> Your mod is excellent, many thanks.

Thanks :)

**Comment by Technici4n** [comment]
> However, keeping the connection might be better, I'll look into it.

This behavior has been implemented, thanks for the suggestion!
You can read the commit message for more details.
