### ISSUE TITLE
Bronze Drill life?

### ISSUE THREAD

**Issue by mnsnownutt** [AztechMC/Modern-Industrialization#121]
MC 1.17.1
MI 0.5.8

I created the steam quarry and a couple of bronze drills and I got a total of 12 tin ore and they were consumed in the process?  Is that intended?  If so, what is the point of the quarry if you consume much more in drills than you ever would get back in resources?

**Comment by mnsnownutt** [comment]
Not sure what happened or if it was a mod interaction issue, but logged back in and it is suddenly working again with the bronze drill back in the machine.  No idea how that is even possible.  I will close this and if it repeats I will open a new one.

**Comment by mnsnownutt** [comment]
It is an issue, or maybe it is a balance question on durability.  After making several drills, I realized it was completely random as to how long they will last.  Here is what I got with the 1st four bronze drills in the quarry.
 
1st drill - 6 tin
2nd drill - 6 tin
3rd drill - 30 iron, 20 tin, 10 redstone, 10 gold, 10 copper (numbers on this one approximate, forgot to take a screenshot)
4th drill - 8 iron, 8 copper

They are basically worthless as is the quarry, due to the materials required to construct them and the complete randomness (apparently) of the drill life.  The recipe to make one drill takes a lot of resources and the gain is minimal, if not negative, even with ore tripling.

**Comment by Technici4n** [comment]
The expected number of recipes per drill is 1/p where p is the consumption probability (p = 0.01 for bronze drills).
So on average you get 100 recipes per drill.
Which yields, on average, per bronze drill:
- 40 iron ore
- 40 iron ore
- 20 copper ore
- 30 tin ore
- 15 gold ore
- 20 redstone ore

There is a x4.5 multiplier for the metals, so you should get a largely positive amount.

Make sure that you didn't lock the outputs and that you had enough slots in the output hatches for items not to get voided.

**Comment by mnsnownutt** [comment]
Screenshot attached.  They go into a chest.

**Comment by Technici4n** [comment]
Are you sure the outputs are not locked? (No orange squares in the output hatches)

**Comment by mnsnownutt** [comment]
Not sure how you lock the outputs (new to this mod).  The item output hatch is set to auto-extract and items flow into the chest attached.
![2021-09-04_06 09 14](https://user-images.githubusercontent.com/31514693/132092362-3e4216cb-738c-49e3-bbf2-6d712fe0eed3.png)

**Comment by mnsnownutt** [comment]
I went into a creative world and recorded a drill, went back into the video and it lasted 42 cycles and this is what I ended up with:
16 coal
10 gold
8 iron
6 tin
4 copper
10 redstone

Frankly, that is better than what I have been averaging, but only 42 cycles on the drill is what I think part of the issue is.  As for the average numbers you listed, I have come nowhere close to that.  Something is off.

I will try another drill  in the creative world and see how many cycles it lasts and the results.

**Comment by mnsnownutt** [comment]
I forgot to hit record, so I am not sure how many cycles I got on the next drill, but this is all I ended up with:

4 copper
8 coal

**Comment by mnsnownutt** [comment]
Did a 10 drill test.  The average number of cycles a drill lasted was 48.1.  However, the average number of ores I got were close to what you had listed:

Coal = 40.0
Copper = 19.6
Gold = 13.0
Iron = 38.4
Redstone = 19.0
Tin = 31.2

So, it may be just being really, really unlucky to get 6 tin on a drill 2 separate times and 4 copper and 8 coal another time.

**Comment by Technici4n** [comment]
Ok, I'm glad that the math is right. Randomness is usually very irregular, that's what you've noticed here! I suggest crafting batches of drills, maybe 8 or 16 at once.

**Comment by Derpford** [comment]
I have Opinions about this, because I played this mod back when the quarry used item pipes instead of drills, and I actually quite enjoyed it that way. The item pipe version made it feel rewarding to make production lines for specific kinds of item pipes, because they were consumed quickly enough that having a large supply was a good idea. The drills are more expensive, and theoretically last longer--but because they last so much longer and require so much more initial investment, I don't know how useful it'll be to mass-produce them.

Honestly, I'd like an alternate setup--maybe a configuration option--where the drill isn't consumed, and instead I have to feed in item pipes, similar to the old system. I'd suggest rebalancing the consumption rate to account for the new, more expensive item pipes--but the general idea is that instead of having a 1% chance to break an expensive item, it's more interesting to have maybe a 25 to 50% chance to break an item I can mass-produce relatively easily.

**Comment by Derpford** [comment]
Also, here's some quick napkin math on how much a bronze drill costs:

At maximum steam-age efficiency, one ingot is equal to 2 rods or 4 bolts. A gear costs 1 rod (ring) plus 4 bolts (2 rods) plus 4 plates, or roughly 5.5 ingots. Each drill thus costs `2*5.5` or 11 ingots of iron, regardless of the main drill material.

The bronze drill costs 2 bronze gears (11 ingots), 3 bolts (.75 ingots), 1 rod (.5 ingot), 2 bronze curved plates (2 ingots) and 1 standard bronze plate (1) ingot for a total cost of 16.25 bronze ingots.

At maximum efficiency, you get 4 bronze ingots per 3 copper and 1 tin. You get 8-12 ingots out of each block of copper ore, and 3-6 ingots out of each block of tin. To pay back the cost of a drill you would need at least one maximum-yield copper ore block, and a tin block that yields 4 or more. Alternatively, 2 of each will probably do just fine. The iron requirement is a bit more painful--iron yields 3-6 just like tin, but you need at minimum 2 max-yield iron ore blocks to break even on the iron gears. 4 blocks of iron ore will guarantee breaking even.

This all sounds perfectly reasonable when the expected yield is 50 cycles or so. However, randomness does not play nice with your expectations, and a bad roll early on can be punishing.

**Comment by Technici4n** [comment]
We highly reduced the raw resource cost of early game (large plates for casings, anyone?), but in turn we increased the required micro-crafting. With the reworked forge hammer in the latest alpha (1.0.0-alpha.0.4), micro-crafting has been drastically reduced. I think that drills are a lot less frustrating with the new forge hammer, which should mitigate bad luck.

Maybe you should check out the new alpha and let us know what you think?

**Comment by Derpford** [comment]
I'm already most of the way through the Steam age in my current playthrough, but I'll give it a shot.

**Comment by Derpford** [comment]
Having played far enough to start looking at the forge hammer recipes: I'm not sure I like this. This technically helps solve the drill problems, because now you can craft maximum efficiency bolts, plates, rods, and rings immediately after getting the forge hammer...

...but the thing is, part of what I loved about this mod was that it had a tangible sense of progression from manual crafting to steam-powered crafting, and every steam machine improved your efficiency in leaps and bounds. You went from needing 4 ingots per ring and 2 per plate to needing 1 ingot per ring or plate the moment you made the compressor. You've solved the microcrafting issues by flattening the progression out.

And that doesn't even fully solve it, because part of what was lost with the item pipe changes is the ability to automate them in the Steam age. The Packer used to be able to craft item pipes, remember? Part of the point of techmods, for me, is setting up automation and then watching it chug along without you--but I can't automate drill production until I hit the *Electric* age.

And then the third problem: The addition of hammers is a reversion. One of the initial goals of this mod was to do away with Gregtech's insistence on crafting new tools constantly. But crafting a Copper Drill cost me the entire durability of my first hammer. 

Instead of getting a progression from low-efficiency manual crafting to high-efficiency automation that has immediate benefits (2 to 4 times crafting efficiency!), I get a progression from a crafting system that forces me to stop and make another hammer every time I make a drill (ugh) to one that...does the exact same crafting at the same efficiency, but replaces the hammer with a lengthy wait.

I hate to break it to you, but I don't think this truly solves the problem. It technically makes drills feel less grindy, but in the process it hamstrings the mod's progression system.

Again, I think the older system where item pipes were the thing being consumed was just better. The resource costs felt balanced compared to the chance of loss and the resources gained, and it felt rewarding to set up a production line that could take the resources from the quarry and skim enough off the top to keep it running. 

What I'd do is have the machine take two inputs--a drill, which sets the output and is never consumed, and either Curved Plates, Chains, or Item Pipes (which are consumed similarly to the item-pipe quarry). If you use Item Pipes, I'd recommend re-adding the ability to craft Item Pipes with a Packer. That said, I think Chains would actually be the ideal item to use as a "cost" item. They'd make use of not only Compressors, Packers, and Cutting Machines, but also the Steam Blast Furnace, and are cheap enough to fit the same role Item Pipes used to. It would be a more complex automation pipeline than Item Pipes used to be in 1.16, but still possible in the Steam Age.

**Comment by Azercoco** [comment]
Thank for your input. We will think about it. We recently reworked the early game so we will focus on the rest of the progression for now but I like your idea of using both the drill and item pipes in the quarry. For the Forge Hammer rework, most of the feedbacks we have are positive so we will likely not change it.

**Comment by Rakkis157** [comment]
I am not sure I like Drills being unconsumable. They are fun to automate once you hit assemblers. Needing to craft only a single drill, then use the really easy to craft item pipes would either break consistency with higher tiers, or just make the higher tier automations less interesting.

Once way you could do it is to let the Quarry just use chains, but have that generate coal and iron, with a low chance of copper, tin and lead. It'll get phased out for Drills eventually, but should serve as an early game option in the post quarry, pre assembler stage, and then later as a way to produce lead in the post assembler, pre electric quarry stage. It would make those two pain points a lot less painful, since you are no longer forced to manual craft Bronze drills, or scrambling to mine lead just to keep your bronze drill production going.

**Comment by Derpford** [comment]
That's a good idea. I'd need to test it to come up with solid numbers, but
I think a 10-15% chance of consuming the chain, with roughly half the yield
per successful roll of a bronze drill, would do nicely.

**Comment by Derpford** [comment]
I did some testing. Here's two examples; each of these is the output from one stack of chains in the quarry, with a 10% chance of chain consumption and 1/2 yield per chain:
![image](https://user-images.githubusercontent.com/10187719/147532572-1b372d06-21cc-4d41-9e32-62afa4bb92dd.png)
![image](https://user-images.githubusercontent.com/10187719/147532309-07f87880-ebdf-4b67-8423-10ba655af1f5.png)

And here's a bronze drill for comparison:
![image](https://user-images.githubusercontent.com/10187719/147532325-6013620d-5a61-493c-9013-1e6725c28d70.png)

More specifically, with the datapack I put together for testing this:
1. Chains have a 10% chance of being consumed.
2. Each cycle takes half as long and produces half as much ore on a successful roll.
3. Iron and Coal both appear with a 5% chance, just like with the bronze drill; however, copper and tin only appear on a 2% chance, and gold/redstone cannot be mined with chains.

The .json file I wrote up for this is in [this gist](https://gist.github.com/Derpford/910ae47501a9190e113e94ae5cf43503).
