### ISSUE TITLE
Forge hammer ore doubling

### ISSUE THREAD

**Issue by tobytes** [AztechMC/Modern-Industrialization#177]
Minecraft: 1.18.1
MI: 1.0.0

The guidebook describes early ore doubling in the forge hammer for iron, copper and tin.

Since minecraft 1.18 mining ore drops raw ore instead of the old ore blocks.
There is no recipe available to get anything doubled from raw ore only from the old ore blocks that can only be obtained by the quarry it seems.

**Comment by Azercoco** [comment]
In order to get the ore block directly, you can use a Steam Mining Drill or a Silk Touch pickaxe.

I've updated the guidebook so that will be more clear and also fix some outdated info. I've also added a Forge Hammer recipe for converting raw ore into dust using a Hammer.  (955a805a00efa0d09d8cfda9fcae08c95092706e)
