### ISSUE TITLE
cannot find any content in manual

### ISSUE THREAD

**Issue by w7iche** [AztechMC/Modern-Industrialization#203]
![Snipaste_2021-12-27_01-20-44](https://user-images.githubusercontent.com/96696414/147415515-94f21d89-24fd-4956-8055-8671849ee2fd.png)
As shown in the figure, check the contents of the manual and there is an error. i dont know how to solve it.(this is modpack"Another Quality Modpack 2 ")

**Comment by jecowa** [comment]
It was an issue with item names used in the Chinese translation being out-of-date. I made a pull request for it in #205 

Here's a build of it if you don't want to wait: https://github.com/jecowa/Modern-Industrialization/releases/tag/untagged-ea64b5948cf5d9ed0e8e

Are you interested in translating the rest of the guidebook to Chinese?

**Comment by Technici4n** [comment]
Ah, thank you! If you want to translate more of the guidebook, that'd be very appreciated! :)

**Comment by jecowa** [comment]
Here's a plain text version of the manual in case this helps anyone translate:

- The Electric Age
- You have discovered that steam can be converted to a new energy. With this innovation, machines can be much more complex and run much faster. Welcome to the Electric Age!
- The Endgame
- You're in the endgame now! Was nuclear fission the only thing that quantum physics had to offer? Of course not!
- The Midgame
- Now that you have mastered the basics of electricity and oil processing, you have the skill and the infrastructure to scale up your factory massively. Welcome to the Midgame! The remaining pages of this guide book will give you the most important information only, the rest is for you to figure out!
- The Steam Age
- You have heard that it is possible to combine copper and tin into a new material called bronze. Perhaps it could be used to harness the power of steam for automatic processing. Welcome to the Steam Age!
- Advanced Machines
- Aluminum
- Aluminum is a material used for making more advanced machines. Like the other electric machines, these new machines will only connect to LV cables. Put bauxite dust in an Electric Blast Furnace and you'll get aluminum nuggets.
- The Centrifuge splits items by spinning them very fast. You can use it to make carbon dust and unlock better recipes for steel and silicon.
- The Chemical Reactor can make items and fluids react.
- The Distillery will turn various fluids into their lighter parts. That will be very useful for Oil Processing.
- The Electrolyzer can split materials into their different parts using strong electric currents. You can electrolyze bauxite dust to get aluminum dust, which you can then directly smelt into aluminum ingots in the EBF.
- Electric Machines
- Electric machines work exactly the same as steam machines, except that they require electricity instead of steam and they progressively overclock recipes up to 32 EU/t. You can use REI to view the recipes for the electric version of the machines you are already familiar with.
- The Polarizer polarizes stuff. It doesn't have many recipes yet, but it is already useful to automate Motors!
- The first machine you'll want to make a lot of! The Assembler allows you to automate almost all recipes, up to 3 per Assembler if you use slot locking.
- We strongly suggest that you automate Machine Hull, Analog Circuits, Motors, Pistons, Robot Arms and Conveyor Belts using Assemblers as soon as possible, that will make crafting electric machines basically free!
- The Configurable Chest is not a machine, but once you have Analog Circuits, you can craft it! It has 21 configurable slots, and auto-extract functionality! Very useful for automation!
- Electric Blast Furnace (EBF)
- The Electric Blast Furnace is the electric version of the Steam Blast Furnace. It unlocks new recipes and like other multiblock electric machines, its overclock is bounded to 128 EU/t by default.
- The EBF is made of one layer of Heatproof Machine Casings, two hollow layers of Cupronickel Coils and one other layer of Heatproof Machine Casings. The controller must go on the bottom layer, and hatches on the top or bottom layer.
- Don't forget to add Energy Input Hatch(es) or the EBF won't have energy! The LV Energy Input Hatch will only connect to LV cables.
- MV Energy Input Hatches will only connect to MV cables, which can be useful if you need a ton of energy for your EBF! You can't craft them yet, but keep in mind they exist...
- Better Multiblocks
- The Electric Quarry is the electric equivalent of the Steam Quarry. Provide it with items and energy, and watch your resources GO BRRR! Its structure is exactly the same as the Steam Quarry's.
- A better and bigger Large Steam Boiler! This advanced version can produce up to 1024 mb/t of steam!
- Electricity
- The Steam Turbine uses Steam to produce electricity. It converts every mb of Steam to 1 EU, up to 32 mb converted every tick.
- The Steam Turbine will automatically send electricity to any machine connected directly to its output side. It will only connect to cables placed on its output side. It has the Low Voltage (LV) Tier. Every electric cable has a Tier which determines how many EU/t it can transfer and to which machines it can connect. Copper, Silver and Tin are LV, Cupronickel and Electrum are MV, and so on...
- Cable networks have limitations on the amount of energy they will pull into the network: at most 256 EU/t for LV cables, 1024 EU/t for MV cables and 8192 EU/t for HV cables. Because there is no output limit for the network and because cables have a small internal storage, an LV network can provide more than 256 EU/t for a short amount of time. Note however that single block electric machines will only connect to LV cables!
- To transfer more energy, you need to either create multiple pipe networks or use Transformers. As you would expect, an X to Y Transformer will connect to Y cables on its output side and to X cables on its 5 other sides.
- Diesel Jetpack and Tools
- Jetpack go brrr... The more powerful the fuel, the faster the jetpack! We recommend Rubber Boots and a Rubber Helmet... Don't forget to activate it using the $(o)Toggle Flight$() keybinding!
- This Mining Drill can finally replace your Pickaxes and Shovels. Fill it with powerful fuel for the best speed! Toggle between Silk Touch and Fortune III with shift right-click.
- Cutting down trees in style!
- Large Steam Boiler
- The Large Steam Boiler is an upgraded version of the smaller Bronze and Steel Boilers. It uses fuels 8 times faster than the Furnace, but it produces 256 mb/t of Steam when fully heated. Don't forget Water or it won't work!
- The main block you'll need is the Bronze Plated Bricks, but you'll also need Bronze Pipe Machine Casings and Heatproof Machine Casings.
- The Large Steam Boiler is comprised of one layer of Heatproof Machine Casings and three layers of Bronze Plated Bricks. The controller goes on the second layer (i.e. the first layer of Bronze Plated Bricks). The two middle blocks are Bronze Pipe Machine Casings. Hatches must be placed on the bottom layer.
- Large Tank
- The Large Tank is a multiblock that allows you to store large amounts of some fluid, for example steam. It can store 64 buckets worth of fluid for every block in the structure (including sides).
- You will only see a preview of the smallest shape, but you can add layers on the top, the back and the sides of the tank. The front face must remain horizontally symmetrical. Only pipes may access the tank, and only through the controller. Don't break the controller or you will lose all of the stored fluid!
- Making Cables
- Mix Coke Dust with Water in a mixer and you will get Raw Synthetic Oil, which you can burn in a Steam Blast Furnace (SBF) to get Synthetic Oil. Mix it with paper and that gives you rubber sheets! Automating this process is strongly recommended! Note that paper can be made from wood using wood pulp.
- For the wires, you will need the Wiremill! Combine these wires with rubber sheets to get cables!
- Oil Processing
- The Oil Drilling Rig is a huge multiblock that can dig for Crude Oil under the bedrock using fluid pipes. Yes, it's an oil quarry basically. Oil processing will give you a ton of byproducts and energy!
- The structure of the multiblock is made of: Steel Machine Casings, Steel Pipe Machine Casings and Chains as you can see by placing the controller and holding a Wrench. The Hatches can be replaced by Steel Machine Casings, but be sure to have at least Item Input, Fluid Output and Energy Input Hatches! Crude Oil can be turned into various fuels and used for more efficient Rubber Sheet production.
- Various fuels can be burned in the Diesel Generator, and you can check in REI how many EU each fuel produces. The Diesel Generator will produce up to 128 EU/t and will only connect to MV cables.
- Diesel Generators will only use fuel when they need to, but if you need a constant supply of energy, you can put liquid fuels in the Large Steam Boiler instead of items. A fully heated Large Steam Boiler will roughly produce twice the amount of energy a Diesel Generator would produce using the same quantity of fuel.
- FUUUUUSION
- The Fusion Reactor is the ultimate energy source! It can combine Deuterium, Tritium, and/or Helium-3 into Helium Plasma, the most powerful fuel in the game!. However, it requires a large amount of energy to ignite the reaction.
- The Plasma Turbine can turn Helium Plasma into EU, at the rate of 100 kEU per millibucket. Its maximum production rate is roughly 1 MEU/t.
- GraviChestPlate
- The GraviChestPlate uses advanced superconductor technology to invert the gravitational field around the player wearing it. It uses EU, and can be charged by right-clicking a block that can output energy.
- Note that the current GSP technology grants fly and prevents fall damage, but it does not protected against other kinds of damage. The Modern Industrialization engineers are trying to find a solution, but R&D is taking longer than expected.
- Quantum Tier
- What happens when scientists try to build a miniature black hole in their lab? The Singularity is the answer: this immensely powerful ball of matter has very useful quantum physics applications with the proper stabilizing materials.
- The Quantum Upgrade is the most powerful machine upgrade ever. Have a look for yourself.
- The Quantum Sword uses the raw power of the Schrödinger equation to instantly vaporize any foe (or friend!) you hit with it.
- Through the gravitational effect of the Heisenberg uncertainty principle, the full Quantum Armor set makes you immune to all damage and grants you creative flight. Each new piece of armour increases by 25% the likelihood of nullifying any damage taken.
- The Quantum Barrel is the ultimate barrel tier: it can hold 2,147,483,647 stacks of a single item!
- The Quantum Tank is the most powerful tank tier: it can hold 2,147,483,647 buckets of a single fluid!
- E = mc²
- With a suitable Electrolyzer setup and a Singularity, large amounts of energy can be turned through Quantum Hawnking Radiation,  into Universally Useable Matter also known as UU Matter, the very fabric of the universe.
- With 100 mB of UU Matter, the replicator can duplicate (almost) any item in the game! Congratulations, it is now Yourcraft. Thanks for playing Modern Industrialization.
- Better Diesel
- Keep in mind you can use a Turbo Diesel Generator for compat HV power generation. As you might expect, it produces up to 512 EU/t. Remember that you can find the amount of energy stored in every fuel with REI.
- Once you have access to processing units and highly advanced machine hulls, considering making a few Large Diesel Generators. Each of these bad boys will turn fuel into EU, up to 16384 EU/t!
- Fluid Pipe Speed
- You might be wondering how you can possibly transfer all these multiple thousands of millibuckets of steam every tick? The answer is: with regular fluid pipes! Each fluid pipe has an internal buffer of exactly one bucket (= 1000 millibuckets). When you connect multiple pipes directly, they become linked and share their internal storage.
- How much fluid is transferred every tick is then bounded by the total capacity of the network. For example, 25 fluid pipes linked together can transfer up to 25000 mb/t of fluid - assuming you can produce that much fluid of course! Note that you might be limited by the transfer rates of the tanks/machines the pipes are connected to.
- High Pressure!
- The Pressurizer is a new multiblock made of titanium that can turn water into HP (high pressure) water, steam into HP steam, and the other way around.
- Once you have access to HP water, you can use a High Pressure Large Steam Boiler to produce HP steam. One millibucket of HP steam is worth 8 mb of regular steam, that is 8 EU.
- A Large Steam Turbine will accept both regular steam (1 mb = 1 EU) and HP steam (1 mb = 8 EU) into EU, and will generate up to 16384 EU/t! However it will not give you back regular nor HP water.
- Remember that pressurizing water into HP water costs a lot of energy, but the turbine will not give it back! You can use a Heat Exchanger to recover the HP water for another cycle.
- Another option for small setups is to use an HV steam turbine. Like other HV generators, it will produce 512 EU/t. This one will only accept regular steam.
- Implosion Compressor!
- A Familiar Blue Gem
- Using Industrial TNT, the Implosion Compressor is able to compress dust and ingots of the most resistant materials. This includes Tungsten, Blastproof Alloy, Beryllium - these materials are very important for nuclear fission - and Diamonds at last!
- Hopefully you have learned to check every REI recipe by now, so you should easily find that Blastproof Mixed Ingots and Tungsten Nuggets can be made with a Compressor... until you have your first Implosion Compressor of course!
- The Nuclear Reactor
- The Nuclear Reactor is a large multiblock whose purpose is to generate massive amounts of energy by consuming nuclear fuel. It can produce 100s of times more EU/t than diesel. It comes in several sizes from small to large.
- How it works under the hood can be a bit overwhelming, despite the following pages trying to explain it. Nevertheless, you don't need to understand the details to be able to design a powerful reactor. We recommend that you experiment with various designs in creative mode until you find one that suits you.
- Note that the Nuclear Reactor cannot explode, emit radiation, or otherwise damage the map. The only thing that it can damage is the items you put in it if the temperature gets too high (more on this later). You should feel free to experiment, and enjoy your new life as a nuclear scientist!
- The main component is the Nuclear Casing which is made with Nuclear Alloy : a mix of cadmium, beryllium and blastproof alloy.
- The upper part of the structure accepts Nuclear Item or Fluid Hatches (or simple casings). Those are the inputs and outputs of the reactor.
- Each hatch has one input (either item or fluid) and two outputs. The input slots will form a grid, displayed in the reactor GUI (accessible by right-clicking on the controller).
- Each hatch has a temperature and stores heat which can be dissipated in several ways. The heat will naturally move to an adjacent hatch or to the outside if the hatch is on the edge (the heat is then lost). The speed of this process is equal to the hatches content's heat transfer coefficient (shown in REI) times the temperature difference. The heat can also be extracted in a fluid hatch by producing steam. A temperature above an item's maximum temperature will destroy it.
- The core nuclear reactor elements are neutrons. Those are produced by the nuclear fuel. There are two type of neutrons, fast and thermal : the fast carry energy while the thermal do not. Neutrons move in a straight line until they encounter an element or exit the reactor (for fast neutrons, their energy is then lost). The flow of neutrons is shown in the reactor GUI.
- When a neutron encounters a non-empty hatch, two things can happen : the neutron is absorbed or scattered. A scattered neutron will randomly change direction. If the scattered neutron is fast, it has a chance of slowing down, becoming a thermal one. This transfers the energy from the neutron to the hatch in the form of heat. An absorbed neutron stops its course and also transfers its energy if it was a fast neutron.
- The number of absorbed neutrons in a single hatch can be seen in the GUI. The probability for each processes is shown in REI. Those will strongly depend on the hatch's content and the neutron type (fast or thermal). Nuclear fuels absorb thermal neutrons far better.
- When a neutron, either fast or thermal, is absorbed in nuclear fuel, more neutrons are generated. Those are always fast neutrons and have random direction. Their generation is accompanied by the direct release of energy in the form of additional heat in the hatch.
- Above a certain threshold, the number of generated neutrons will decrease with the temperature until reaching zero. This process wastes some energy, but guarantees the stability of the reactor. The number of generated neutrons (and effective efficiency), the direct energy and the temperature threshold are in REI.
- Each nuclear component has maximum number of absorptions. When reached, the item is either destroyed or transformed into a depleted version. This is particularly useful for nuclear fuel because some part of the U238 is transformed into Plutonium in the depleted version, meaning some of it can be transformed back into fuel.
- The same thing happens for fluids: a bit of fluid is transformed after each neutron absorption. This can be used to mass produce useful isotopes like deuterium and tritium. In both cases, the outcome is shown in REI.
- Stainless Steel
- Stainless Steel
- Stainless Steel is the next material you will want a large quantity of. Read on to know why! Smelting stainless steel dust in an EBF will give you hot ingots, which you can cool back into regular ingots with a Vacuum Freezer.
- You can check the base materials with REI, and the exact shape with a wrench!
- Once you get some digital circuits going, make sure to build a Distillation Tower. The Distillery only gives you one oil processing output, but the tower gives you ONE PER LAYER!
- To change the height of the Distillation Tower, right-click it with a screwdriver. This applies to other multiblocks with multiple shapes as well, such as the Kanthal tier EBF.
- Upgrades!
- Overclock Upgrades
- You know that regular electric machines have an overclock capped at 32 EU/t, and electric multiblocks have an overclock capped at 128 EU/t? Right-click the machine or multiblock with some upgrades in your hand to increase its maximum overclock! Check REI for the exact amounts.
- Shift right-click a machine with a crowbar to drop the upgrades it contains. Right-click it to remove its upgraded hull and change it back to LV tier. Wait, you can do that? ...
- Machine Hull Upgrades
- Yes you can! Right-click a machine with an Advanced Machine Hull to change it to MV tier: it will now accept MV cable connections only. Right-click with a crowbar to remove the upgrade.
- Hot Water
- Steam machines need steam to function, and that's exactly what the boiler provides. It will slowly use fuel to heat up. When it's hot enough, it will start to produce steam. Don't forget to feed it with water or your fuel will burn for nothing.
- You can also smelt water buckets into steam buckets. Make your first Bronze Compressor before the boiler to save a lot on the plates! Turn the page for the boiler itself...
- It probably looks expensive to you right now, but don't forget that you can triple ores with the Forge Hammer. Also, as soon as you will have your first two machines, it will become more than twice less expensive!It probably looks expensive to you right now, but don't forget that you can triple ores with the Forge Hammer. Also, as soon as you will have your first two machines, it will become more than twice less expensive!
- Do You Like Coke?
- Once you have had enough of the bronze machines, you can start working toward making steel. The ultimate goal is to be able to build the quarry, a multiblock that will dig ores for you! The first step is to make coke, by heating coal without oxygen. For that, you will need to build a Coke Oven multiblock.
- For this first multiblock, you will need the Coke Oven itself of course, 21 Bricks and 3 Hatches: an item input, an item output and a fluid input.
- The Coke Oven block here has the role of a Controller. Every multiblock is managed by a controller, but you usually cannot interact with the controller directly: all input and output goes through hatches. We need a fluid input because the coke oven is powered by steam, we need an item input for the coal and an output for the coke. If we forget one of the hatches, the coke oven will not be able to start!
- Hold a Wrench to see the missing blocks and the errors! You can also hold a Hatch to know where it can go. We need 21 Bricks for this multiblock! Check REI, it says 24 total, but we have 3 hatches so we only need bricks for the 21 remaining blocks!
- There are many ways to place the hatches, this is one of them!
- Coke Oven!
- Once the Coke Oven says "Shape Valid", fill the fluid input hatch with steam, put coal in the item input hatch and you're good to go! Coke will be very useful for steel, but it is also a powerful fuel. It lasts 4 times as long as coal!
- Getting Started
- Before making bronze, we will need to create a Forge Hammer. It is used for basic processing steps. You can put iron, copper and tin ore in the forge hammer and you will receive 2 raw ores per ore. You can increase this ratio by using a Hammer. Every raw ores can be smelted into an ingot.
- The Hammer increases the ratio in the Forge Hammer and unlocks more recipes, at the cost of some durability.
- Now, you may want to consider making a Steam Mining Drill to obtain the ores directly without needing a Silk Touch pickaxe.
- The Steam Mining Drill can mine 3x3 blocks at the time, perfect for your early game mining needs! It also has Silk Touch which combines well with the Forge Hammer.
- The Steam Mining Drill requires both water and solid fuel (for example coal). Right-click a water source to fill it with water, and make sure to always place some fuel in your drill by right-clicking the fuel items on it in your inventory. The fuel will be consumed slowly when you mine.
- Your First Bronze!
- First, you need to make copper and tin (tiny) dusts by hammering copper and tin ingots (nuggets) in the forge hammer. You can then combine copper and tin (tiny) dusts to make bronze (tiny) dust. This process is more efficient in a Mixer. Always remember that 9 tiny dusts are one dust.
- Smelting bronze dust will give you a bronze ingot.
- Pipes
- Pipes are used in the recipes of some machines, but they can also be placed in the world. Up to 3 pipes can fit in a single block. Pipes of different colors will not connect. Right-clicking a pipe with a wrench will change the connection type, shift-right-clicking will drop the pipe.
- Fluid Pipes
- Fluid pipes can only contain one type of fluid, and by default they won't connect to empty pipes or blocks. You can force a connection by right-clicking the center of the pipe with the wrench, or by right-clicking a block with a pipe in your hand: it will connect, but not consume the item in your hand.
- Item Pipes
- Item pipes will not connect to inventories by default, but again you can force a connection. Right-click a connection without holding a wrench and will see a filter. By default, whitelist mode is enabled, so no items will be inserted or extracted directly.
- The different types of pipes don't work exactly the same way. Every tick, fluid pipes will try to evenly extract for all connected blocks, and then try to insert that evenly. Read more about their speed here. Item pipes will insert items into higher priorities first, and they will transfer 16 items every few seconds. They can be upgraded with motors.
- Note:
- The item pipes are on whitelist by default (which mean only the items in the filter will be moved). You need to switch to blacklist (only the items NOT in the filter will be moved) or add the item you want to move to the filter. Be careful that you need to configure both sides of the pipe, otherwise items will not move.
- Infinite Resources?
- The Steam Quarry
- The Steam Quarry is a steam multiblock machine that consumes bronze drills, uses them to dig deeper than the bedrock and gives you back some ores, as you can see in REI. It's recommended that you have multiple SBFs running before you attempt to build it because it requires a lot of steel.
- If this is the first multiblock you are building, make sure to read the Coke Oven entry! It explains how multiblocks work, how to check if the structure is correct, and how to use hatches.
- Steam Machines
- Now it's time to build some bronze machines. The boiler will automatically produce and send steam to adjacent machines, up to 8 millibuckets per tick. Bronze machines can only process recipes up to 2 EU/t, meaning that the recipe will use 2 Energy Units per Tick. As 1 millibucket of steam = 1 EU, a boiler at max temperature can power 4 machines simultaneously!
- The Compressor will turn ingots into plates at 1:1 ratio. It can also turn each double ingot into 2 plates. This is probably the first machine you will want to build!
- The Mixer will help you mix dusts, giving you a better ratio for bronze, fire clay and later uncooked steel. It can also create cobblestone and clay.
- The Macerator will turn 3 crushed dusts/raw ores into 4.5 dusts. Ore hemiquadrupling for the win! It can also recycle all kinds of materials by turning them into dust.
- The Cutting Machine will give you better ratios for bolts, gears, rings and rods. It uses a little bit of lubricant every time.
- The Furnace is... well... a Furnace. It is as slow as normal Furnaces, but it uses 20 times less fuel because steam is very efficient.
- Steam machines will accept inputs from any side, be it items, steam or another fluid. You can lock their slots by clicking on the lock in the interface. Locked slots only accept one type of item or fluid. Every machine has an output side, and you can enable auto-output from the interface. Hoppers, pipes and other automation can extract output items from any side, of course. You can also reduce the maximum number of items in a slot by scrolling.
- Using a wrench, you can rotate any machine by right-clicking. You can rotate the output side by sneaking while you shift-click. Note that breaking a machine with the wrench will not drop it. Use a pickaxe for that!
- Upgrading To Steel
- Now that you have steel, you can upgrade your bronze machines if you want. Steel machines can process recipes up to 4 EU/t, and they will process recipes at twice the speed as long as the energy usage doesn't go above 4 EU/t. Basically, they are twice as fast as bronze machines and they may also unlock new recipes.
- To upgrade a bronze machine, craft a Steel Upgrade and apply it in a Smithing Table.
- Steel hatches have more capacity than bronze hatches, and a multiblock with at least one steel hatch will be upgraded to steel tier. This means that it will go twice as fast if its energy usage wouldn't exceed 4 EU/t. A steel boiler will produce twice as much steam as a bronze one, that means up to 16 EU/t, and a steel water pump will produce twice as much water as its bronze counterpart, so up to 2 buckets / 5 seconds.
- Steel tanks store up to 8 buckets. Steel pipes are equivalent to other kinds of pipes, but you can combine them with other types of pipes on the same block, so they may be useful if you really need another distinct pipe network. You can check all recipes in REI!
- The Packer, a new machine only available in steel, can perform simple crafts for you. You can now automate double ingots and pipes, for example! Again, check REI.
- The Unpacker, a new machine only available in steel... Guess what it does. o_O
- With a few steel plates, you can now craft a very useful block! The Automatic Trash Can will destroy any item or fluid that is piped into it!
- Your First Steel
- You can macerate coke to obtain Coke Dust, which you can combine with iron to get Uncooked Steel Dust. Using the mixer will give you a better ratio, of course. Now, you will need a Steam Blast Furnace to turn that into steel. Craft the controller, 29 Fire Clay Bricks and the same three hatches as the Coke Oven.
- The Blast Furnace's structure is the same as the Coke Oven's, with Bricks replaced by Fire Clay Bricks and one extra hollow layer on top.
- Tanks & Barrels
- Bronze tanks can store 4 buckets of fluid each, you can use them to interact with machines, and you can place them in the world. Bronze barrels can be used to store and move 32 stacks of one item. Check the next pages for more information!
- When placed in the world, you can right-click them with buckets or other tanks to transfer fluids. Also, you can stack them if they have the same contents. How nifty!
- If you break a barrel it will keep its stored contents, and you will get an item that you can interact with. Left-click on a barrel item with an item to insert it into the barrel. Left-click the barrel item on an empty slot to extract some items from it.
- You can't interact with barrels that are placed directly, but pipes and machines can just fine.
- Infinite Water?
- You may have been wondering if perhaps there was a way to insert water into the boiler automatically? There is! That's exactly what the water pump does. Surround it horizontally with water blocks, and it will start producing water for 1 EU/t. It will automatically transfer water to the adjacent blocks.
- The Bronze Water Pump will produce 1/8th of a bucket of water for every adjacent water source every 5 seconds, for a max output of 1 bucket / 5 seconds.

**Comment by jecowa** [comment]
Here's a version of the mod with a google-translated manual, if you want to try it: https://www.mediafire.com/file/3dvbi9445fp2ifn/Modern-Industrialization-1.0.2g1.jar/file

**Comment by Technici4n** [comment]
Fixed in #209, thanks!
