### ISSUE TITLE
Suggestion: Move AE2 Silicon compat recipe.

### ISSUE THREAD

**Issue by Derpford** [AztechMC/Modern-Industrialization#23]
Right now MI's AE2 compat recipe for AE2 Silicon is...smelting MI's quartz dust. Thing is, smelting MI's quartz dust *also* produces regular Nether Quartz, since that recipe also exists (solely for MI's quartz dust). This means that we still can't really smelt AE2 silicon from NQ, because the NQ Dust > NQ recipe apparently has priority.

There are two possible suggestions I have for this. I don't have any strong preference for one or the other.

1. Move the dust > netherquartz recipe to the Compressor. This introduces a complication to the production line--adding another material that requires special processing. Meanwhile, the AE2 silicon recipe can stay on *smelting* nether quartz, leaving AE2's balance exactly where it is.

2. Move the AE2 compat recipe to *MI Silicon*. What I would do is make AE2 silicon the result of smelting an MI silicon plate--this is a close approximation of a "realistic" silicon production line without having to add any new machines or items. You could also increase yield when using N-doped or P-doped silicon plates, to reward players who are able to automate more stuff. This would soft-gate AE2 behind silicon production, which IMO is a good thing because AE2 really needs electrical power to work anyway. Players could still do some very early-game AE2 stuff by using Certus Quartz for silicon, of course, but Certus Quartz is incredibly valuable early on, so the optimal play is really to wait for silicon production.

**Comment by Technici4n** [comment]
Hey, thanks a lot for the very detailed issue reporting! We appreciate it **enormously**!

We have decided to go for option 1 because it's exactly what we did for coal and it makes the most sense. I don't know why we added smelting in the first place.

Regarding option 2, we think it would certainly make things more interesting, but we don't want to change other mods' balance. We really don't want to go down the GregTech path, leading to exclusion from most mod packs and thus most of the player base. We leave the job of balancing the progression of other mods to the pack devs, if they want to.
