### ISSUE TITLE
 nerf coke

### ISSUE THREAD

**Issue by m44ster** [AztechMC/Modern-Industrialization#255]
coke currently removes the incentive to use diesel for energy and in some case the incentive to use carbon dust instead of coke dust.

**Comment by Treep3r** [comment]
I did some rough calculations on this, here are my thoughts.


So on average a fully overclocked electric quarry with a bronze drill and no upgrades will yield you 40 Coal ore per 100 operations (average life time of a drill).
This will take around (30s*100)/16 = 187.5s
(I am unsure about the speed the quarry reaches, but measuring shows around 16x like other machines, too)
The 40 Coal ore will yield you 40*4.5 = 180 dust

So on average you gain around one coal dust per second.

A single coke dust will last around 12-15s (don't have the exact number) in a large advanced steam boiler.

Turning all the coal dust you get from your quarry into coke  (yes, it takes 30 coke ovens) will thereby allow you to power 12-15 large advanced steam boilers.
Which equates to 12*1024EU/t = 12.2888EU/t (up to 15.360EU/t)
With that much steam you can almost fully power a large steam turbine!


Now for diesel production.

From the oil drilling rig, you'll get around 50 buckets of crude oil per aluminum drill.
This will take around (10s*100)/16=62.5s
The 50 buckets of crude oil will yield you 30 buckets of diesel.  (Forget about turbo diesel for now)

So on average you'll gain around 500mb of diesel per second.

Diesel can be turned into energy straight away (which makes the HP large steam boiler useless?), making it 500*200EU per second = 100,000EU/s
Which equates to 5000EU/t.
Even turning the diesel into turbo diesel, you only get it up to 10,000EU/t.

And this doesn't even factor in that in order to have an oil drilling rig running at full overclock, you'll need triple(!) the aluminum drills compared to the amount of bronze drills you'll need in the electric quarry.
And then aluminum drills are a lot more expensive to produce.


Correct me if I did any mistakes but the way it looks, diesel energy is just a supplement to your steam power production (since you need oil refining for other things).
The only advantage diesel really has is that you'll need way less space, as the steam setup needs 12-15 boilers and 30 coke ovens.
I don't know it that's supposed to be the only upside to diesel but just a simple buff to the oil drilling rig (more yield per cycle? less consumption of drills?) would already go a long way into making diesel more reliable and viable.

**Comment by Technici4n** [comment]
Isn't coke balanced in the steam age? The problem is just overclock then. We could buff diesel somewhat, but a coke nerf might also be necessary.

**Comment by yorii** [comment]
You practically have infinitely scaling access to coal and lignite coal via quarrys anyway, why waste time even producing coke past the electric age?

**Comment by m44ster** [comment]
> Isn't coke balanced in the steam age?

not sure I mean it's 4 times as much energy but it's not really unbalanced because you need a lot of energy in the early game
> We could buff diesel somewhat, but a coke nerf might also be necessary.

yeah buffing diesel is a good idea
if you also want to nerf coke here are a few suggestions:
less coal and lignite coal from copper and steel drills
only 3 times as much energy as normal coal
(5 instead of 4 steel in the blast furnace with carbon dust)
> You practically have infinitely scaling access to coal and lignite coal via quarries anyway, why waste time even producing coke past the electric age? There is no incentive to use any of the fuels you mention when you can just build as many boilers as you want running on basic lignite coal dust, all you need to do is add more quarries.

I mean coke ovens are really cheap and easy to build and they give you more than 4 times as much energy
while scaling the drill production can mean upgrading a lot of different machines or building new ones

**Comment by yorii** [comment]
Buffing diesel again seems like a great idea, but nerfing coke or in particular nerfing coal output from quarries is a super bad idea, it will just lead to even worse cases of hoarding several millions of iron and gold just to maintain a coal production.
