### ISSUE TITLE
Client crash NPE- Tesselating block in world - Indigo Renderer 	at aztech.modern_industrialization.pipes.impl.PipeModel.emitBlockQuads

### ISSUE THREAD

**Issue by ProsperCraft** [AztechMC/Modern-Industrialization#28]
https://gist.github.com/ProsperCraft/35c44217a0be7c15a4fbcc931f43b516

Player on our server said he click on a waystone and his client crashed.

He has not been able to reproduce the crash.

**Comment by Technici4n** [comment]
Hi, I am surprised that this crash happened!
I am closing this for now because it's not possible in theory, but I just added a bit of debug information in e7ba413, it will be in the next release.
If this happens again, please let me know, hopefully we'll have access to that debug information! Thanks for reporting!
