### ISSUE TITLE
Version 1.2.1 broke item/block IDs in combination with other mods

### ISSUE THREAD

**Issue by M0dEx** [AztechMC/Modern-Industrialization#345]
## Description
Version 1.2.1 broke item/block IDs in combination with other mods (AE2, Tech Reborn).

This is what I see in my world after upgrading from v1.2.0 to v1.2.1 (was a Fusion Reactor from Tech Reborn before):
![2022-06-25_00 54 48](https://user-images.githubusercontent.com/18428519/175720786-ff95d7c5-0b0a-481c-b985-211146c52899.png)

## Version info
**Minecraft version:** 1.18.2
**Mod loader + version:** Fabric 0.14.8

**Comment by Technici4n** [comment]
Hi, adding a few blocks is not supposed to cause such issues. In fact, many people updated successfully. This is probably a bad interaction caused by another mod, or it might also be a client/server syncing issue if you see the wrong blocks on your client, but the server still sees the right ones. Unfortunately, I am not able to help you further. :/
