### ISSUE TITLE
Submit new Chinese language documents

### ISSUE THREAD

**Issue by Gengzi-Isu** [AztechMC/Modern-Industrialization#384]
I added the translation of fluid names in the Chinese lang file. Now it will not only display the id name. If possible, I hope you can adopt this supplement. thanks.
[zh_cn.zip](https://github.com/AztechMC/Modern-Industrialization/files/9666421/zh_cn.zip)

**Comment by Gengzi-Isu** [comment]
I forgot to specify the version of the lang file. It is version 1.2.2.

**Comment by Technici4n** [comment]
Thanks a lot, I committed your translations, and they will be in the next 1.19 release. If you want to translate more entries, please have a look at the following file: https://github.com/AztechMC/Modern-Industrialization/blob/master/src/generated/resources/assets/modern_industrialization/lang/untranslated/zh_cn.json. The missing entries are highlighted with `[UNTRANSLATED]`.

PS: the missing fluid translations are due to an error in Porting-Lib used by Create. It's something _they_ should fix, not us.

**Comment by Gengzi-Isu** [comment]
> Thanks a lot, I committed your translations, and they will be in the next 1.19 release. If you want to translate more entries, please have a look at the following file: https://github.com/AztechMC/Modern-Industrialization/blob/master/src/generated/resources/assets/modern_industrialization/lang/untranslated/zh_cn.json. The missing entries are highlighted with `[UNTRANSLATED]`.
> 
> PS: the missing fluid translations are due to an error in Porting-Lib used by Create. It's something _they_ should fix, not us.

In fact, for the time being, you can add the translation of the corresponding fluid key in the lang file, which can make it display the name correctly. This is an appropriate solution at present, and you can adopt it. Thank you.（This is also the last resort.lol）

**Comment by Technici4n** [comment]
No. There's another solution that we could use, but I don't want to release another 1.18 version.
