### ISSUE TITLE
Balance: Machines use massively too much resources to craft

### ISSUE THREAD

**Issue by Seegras** [AztechMC/Modern-Industrialization#49]
All the crafting recipes use massively too much resources. A stack of bronze for one pump is just ridiculous. They all would be okay without the introduction of another middle layer of "large plate" or "brick tiny dust" or some pieces and bobs for the rotors.

xbCrafted isn't impressed either: 
https://www.youtube.com/watch?v=2BG3599Krj8

**Comment by Binero** [comment]
Once I had a steel quarry up I felt like it was rather balanced, but that initial investment was definitely very high! Perhaps make a lower tier quarry that is cheaper but worse to bridge the gap? A bronze quarry perhaps, that is smaller in size?

**Comment by Technici4n** [comment]
Ore tripling is a thing, and you basically don't need to mine at all once you get your first quarry. To balance this, you need to mine a lot of ores to get there in the first place. Making the quarry less expensive would reduce how much of an accomplishment it feels - ultimately this would be a bad decision.
Yes, MI is more expensive in the early game than your typical Thermal Expansion clone, but that's intended and it feels balanced once you reach the electrical age.

**Comment by Seegras** [comment]
It's not about the quarries; it's the basic bronze stuff, boiler, pump, coke oven and blast furnace. And some other assorted bronze machines. It's about factor 8 too expensive.

**Comment by Technici4n** [comment]
That's because you are comparing MI with other mods. But if you search caves for ores, make a forge hammer ASAP and craft the machines in the correct order (boiler, compressor, macerator, mixer, cutting machine, water pump) it's alright.

**Comment by Derpford** [comment]
It's not even about making the machines in an optimal order; each one provides a serious efficiency boost on its own. The Compressor is the biggest one, because it halves the cost of plates, effectively taking you from 128 ingots per machine to 64 ingots per machine--but the mixer is also a big deal, since it takes you from 3 bronze per crafting cycle to 4 bronze per crafting cycle. The macerator enables ore tripling, as well, and combining the Mixer, Compressor and Macerator means that for every 48 copper and 16 tin you get 3 bronze machines.

I personally love it. It actually feels like mass-producing ores is *worth* something, because the scale on which you consume resources is large enough that you aren't making meaninglessly large piles of ingots that you'll never actually use.
