### ISSUE TITLE
[Bug] Enabling liquid auto extraction in any mixer crashes the game/server

### ISSUE THREAD

**Issue by masoncutting** [AztechMC/Modern-Industrialization#71]
Please note that I am using the All of Fabric 3 modpack version 2.8.4. If this is a comparability issue, let me know and I will post it there.

When using the bronze, electric, or steel mixers, if you enable auto fluid extraction without any fluids in the machine, it will crash the game in singleplayer or the server in multiplayer. With that, any time that chunk is loaded, the game or server will crash again, meaning in singleplayer the world is permanently gone without any form of world editing.

To reproduce, place down any of the mixers, open its interface, and toggle the fluid auto extraction and it will throw the following error: java.lang.IllegalArgumentException: You should never test a FluidFilter with an empty fluid!

Crash report: https://pastebin.com/b4fqGtGv

**Comment by Gaurdein** [comment]
Hey, I had the same issue just today. It's already fixed in the next version, but it's recommended to use alpha.10 (or newer in the future)
You have to download the newer .jar files from GitHub's Actions page, it will download a .zip from you have to use the "Modern-Industrialization-0.4.0-alpha.10.jar" file. Copy this into your client's and server's mods folder, and delete the previous one (probably "Modern-Industrialization-0.4.0-alpha.08.jar").
Hope this helped :)

**Comment by Technici4n** [comment]
(Note that they should be downloaded from Curseforge, github is mostly for changelog)
