### ISSUE TITLE
MI pipe crash/softlock Neoforge 1.20.4

### ISSUE THREAD

**Issue by Saereth** [AztechMC/Modern-Industrialization#745]
Originally reported here on the FTB Neotech tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5353

neoforge 20.4.237
Modern-Industrialization-2.0.21-all

If you have a item pipe connected to a cargo manager from steve's carts and its pulling from a side that is set to insert into a cart or extract from a cart but isn't filtered to anything specific (Like engine compartment, etc) then eventually it will cause a soft lock crash where you can't get back into your world

Steps to reproduce
Add MI item pipe on any side of cargo manager and set to pull
Set cargo manager to default settings
Have steves cart dock into cargo manager

Log provided:
https://pastebin.com/Fbsuw0dc

**Comment by Technici4n** [comment]
Thanks for the report. Steve's Carts is not passing the block entity when retrieving the pipes' drops. MI can either crash or silently ignore this and risk voiding the pipes. I chose the former.

I think that this should be fixed in Steve's Carts by passing the block entity in the loot context. (Maybe they shouldn't be mining block entities anyway?) I opened an issue on their tracker: https://github.com/CreeperHost/StevesCarts2/issues/39.
