### ISSUE TITLE
Crash when pressing the "Config" button on Neoforge 1.21

### ISSUE THREAD

**Issue by truepurpledino** [AztechMC/Modern-Industrialization#809]
The game crashes if you press the Config button in the Mods menu on Neoforge 21.0.134-beta, so do many other mods (https://github.com/neoforged/NeoForge/issues/1357, https://github.com/blackd/libIPN/issues/21).

Here's the crash log: https://mclo.gs/fDFyHYm

**Comment by Technici4n** [comment]
You have to update to Cloth Config `15.0.128`.

**Comment by Rheckar** [comment]
> You have to update to Cloth Config `15.0.128`.

I have the same problem ever since I switched from forge to neoforge and any time I try to use the config button the game crashes no matter how many mods there are 1 or 70. For example I have the 15.0.128 version of Cloth Config but config still crashes the game. I also can't run the game with the configured mod which could be the problem but the game gives an uncaught parallel processing error.

**Comment by Technici4n** [comment]
Make sure you are on the latest NeoForge AND Cloth Config.
