### ISSUE TITLE
Vanilla Item Sorter not working when Modern Industrialization is installed

### ISSUE THREAD

**Issue by colingalindo** [AztechMC/Modern-Industrialization#83]
Minecraft version: 1.17.1
MI version:  0.5.3

Current mod list:
Architectury API (Fabric) 2.2.21
Cloth Config API (Fabric) 5.0.34
Fabric API 0.37.1
Modern Industrialization 0.5.3
Roughly Enough Items Fabric (REI) 6.0.264

I originally discovered this while playing All of Fabric 4 and was able to narrow it down to MI.
When creating a vanilla item sorter the hopper never ends up locking. If I force a block update on the hopper when there are the correct number of items in it, then the comparator will correctly respond.

Let me know if any more information is needed.

![ItemSorter1](https://user-images.githubusercontent.com/2458176/127376170-b90d1047-5c36-48bc-8301-84bb9d9c5e4e.PNG)
![ItemSorter2](https://user-images.githubusercontent.com/2458176/127376167-81fa7b53-f703-4117-90d1-b48e15bca6c2.PNG)

**Comment by Zefirrat** [comment]
I though it was a bug of 1.17.1 version but saw this issue. I think this cause hopper does not refreshes his redstone signal strenght or comparator does not refreshes the value of hoppers redstone signal. Because as result of my experiments, when broke and place  again comparator redstone signal resets and then bottom hopper blocking again (redstone torch does not receives signal). But when it activates again (items in hopper enough to get torch) signal never goes less and all items goes to chest.

**Comment by Technici4n** [comment]
I have it figured out, no worries. It was due to a bug in FabricMC/fabric#1553.

**Comment by colingalindo** [comment]
Thanks for fixing this!

**Comment by Technici4n** [comment]
Np, thanks for reporting!
