### ISSUE TITLE
[Bug] When install overdrive module, all the machines don't work.

### ISSUE THREAD

**Issue by SMFDrummer** [AztechMC/Modern-Industrialization#903]
## As title, the machine should run as usual, but when I install this overdrive module, all the machines only cost the elec but not work.

![image](https://github.com/user-attachments/assets/e28bea9a-aa02-48f5-b444-ae56147195e1)

## This is uninstall the module and machine being working.

![image](https://github.com/user-attachments/assets/1284d8b3-7b0b-42a0-a00f-cdc9dff5a58b)

**Comment by Swedz** [comment]
Unable to reproduce. I see you are on Craftoria, are you on the latest version?

**Comment by Technici4n** [comment]
You probably tried to use the machine for another recipe. That's not gonna work.

**Comment by Deleard** [comment]
Noticed that the overdrive turns off if you change the resource in the car.
If the same resource is processed without taking out the overdrive, the machine does not turn off.

**Comment by Swedz** [comment]
What do you mean the overdrive turns off? If you mean it wont run, that is intentional.

**Comment by SMFDrummer** [comment]
> What do you mean the overdrive turns off? If you mean it wont run, that is intentional.

Overdrive can only keep only one crafting recipe，if you want to change another material，please take off the overdrive until the overspeed down to 0.

**Comment by Swedz** [comment]
That is intentional

**Comment by Deleard** [comment]
Sorry, writing through a translator.
SMFDrummer wrote correctly : 
“Overdrive can only save one crafting recipe, if you want to change another material, take the overdrive off until the overdrive speed drops to 0”.

That's why I put a separate overdrive machine for each recipe. Yes, it is more expensive, but I haven't thought of any other solution to the problem yet.

In some cases I use “Time in a bottle” (from another mod) to “speed up” the process to the desired speed.

Translated with DeepL.com (free version)
