### ISSUE TITLE
Compat Support & Feature request

### ISSUE THREAD

**Issue by bookerthegeek** [AztechMC/Modern-Industrialization#930]
## Heyo!
Good day good gentlemen and women! I have a request for you fine people today... Would you please consider adding the following mod compatibility and features to your lovely mod?

### Compatibility:
- Built in native [CraftTweaker](https://github.com/CraftTweaker/CraftTweaker) support.

### Feature:
- ~~The ability in the configs to specify preferred modID for ores and materials? So for example, in the configs I could specify that I would like to have [FTB Materials](https://github.com/FTBTeam/FTB-Materials) as the preferred modID, and then if that item exists in FTB Materials it would output their version of said item instead of yours? This is implemented in other mods such as [Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering), [Railcraft Reborn](https://github.com/railcraft-reborn/railcraft), and others.~~ EDIT: Use [AlmostUnified](https://github.com/AlmostReliable/almostunified) instead.

### Conclusion
I just want to say thank you for the wonderful mod and thank you for taking the time to consider my request. I hope you have a wonderful life, and look forward to what you all implement into this mod, or create in another mod, in the future. Have a great day!

**Comment by Swedz** [comment]
If you use the Almost Unified mod you can achieve this with all mods without the need for individual mods to change to add support for it.

**Comment by bookerthegeek** [comment]
I actually have never played with that mod. That will save so much scripting things out. Thank you for point that out. I'll modify my original post to reflect that information.

**Comment by Swedz** [comment]
MI has built-in KubeJS support, and I do not think there are any plans to add support for CraftTweaker. CraftTweaker does allow you to create raw json recipes in their scripts (similar to KJS), see [here](https://docs.blamejared.com/1.21.1/en/vanilla/api/recipe/manager/GenericRecipesManager#addJsonRecipe). You can also [create functions](https://docs.blamejared.com/1.21.1/en/zencode/Functions#declaring-a-custom-function) to simplify the process for yourself. That is, of course, if you're required to use CraftTweaker. I would recommend using KubeJS since more mods tend to have built-in support for it these days over CraftTweaker.

**Comment by bookerthegeek** [comment]
Fair. Thank you for looking over my request.
