### ISSUE TITLE
Incompatibility with DimThreads

### ISSUE THREAD

**Issue by SrRapero720** [AztechMC/Modern-Industrialization#944]
Hi! i am the author of DImthreads here
Some users reports me crashes on your mod when dimthreads is present and some buggy behaviors.

I am aware of what causes the issues so here is some potential solutions (benefical for both)

**About the buggy behaviors**
https://github.com/AztechMC/Modern-Industrialization/blob/deaf91304cc21a79d9dee7962c27ba5104c13a22/src/main/java/aztech/modern_industrialization/machines/multiblocks/world/ChunkEventListeners.java#L80

Multiblock doesn't need to run that ensurance of the thread because its running on the same level, chunkloading is async but chunk ticking is always "sync" on its own level (other mods can do async ticking  on chunks but is a bad idea). Despite that, you can safety avoid any concerns of it using `MinecraftServer#execute()` or `ServerLevel#getServer().execute`. Is the approach that Dimthreads also takes for sensitive task like entity teleporting.

**About the crashes**
https://github.com/AztechMC/Modern-Industrialization/blob/deaf91304cc21a79d9dee7962c27ba5104c13a22/src/main/java/aztech/modern_industrialization/machines/multiblocks/world/ChunkEventListeners.java#L95-L97

Same as above... But this can be patched on my side. Mosly because dimthreads are "the server threads" of the level.

I want to hear more about why this was implemented like that, so i can help on investigate how to make a stable patch for the both sides :)

**Comment by Technici4n** [comment]
I don't want to support dim threads.

**Comment by Fr3shlama** [comment]
From a threading perspective, those three lines don’t really protect anything, they just hard-code an assumption about how the server should work and then explode if reality disagrees:

```
if (world instanceof ServerLevel serverLevel && serverLevel.getServer().isSameThread()) {
    ...
}

if (!server.isSameThread()) {
    throw new RuntimeException("Thread is not server thread!");
}
```

On a normal setup, this is basically a no-op: chunk events are already fired on the level’s tick thread, and isSameThread() is just confirming something that’s already guaranteed by the caller. So in the “vanilla” case, the check adds nothing except extra noise.

Where it does have an effect is exactly in cases like DimThreads – i.e. anything that doesn’t match your very narrow idea of “the one true server thread”. Instead of doing the sane thing (queue work back onto the correct thread with MinecraftServer#execute / ServerLevel#getServer().execute), the code just throws a runtime exception and calls it a day.

So you end up with:

No extra safety in the standard case

Instant hard crashes in any environment that dares to be more advanced than “everything on one global thread”

If the goal was to make the code more robust, this is about the least effective way to do it. A proper thread handoff to the appropriate executor would both avoid the crash and handle the “we’re not on the main tick thread” case correctly, instead of just rage-quitting the JVM.
